---
- name: Set OS-specific facts for current host
  ansible.builtin.set_fact:
    os: "{{ os_vars[ansible_os_family] }}"
    postgres_data_dir: "{{ os_vars[ansible_os_family].postgres_data_dir }}"
    httpd_conf_file: "{{ os_vars[ansible_os_family].web_server_conf_file }}"
    webserver_path: "{{ os_vars[ansible_os_family].webserver_path }}"
