#!/usr/bin/env bash
# Apply default values for Terraform/Ansible deployment variables.
# Only sets variables that are unset or empty.

# --- General ---
AWS_REGION="${AWS_REGION:-ap-southeast-1}"
OWNER="${OWNER:-ksahu-ygulati}"
ENVIRONMENT="${ENVIRONMENT:-development}"
TERRAFORM_VERSION="${TERRAFORM_VERSION:-latest}"

# --- Cloudera versions ---
CM_VERSION="${CM_VERSION:-7.13.2.10000}"

# --- AWS existing resources ---
EXISTING_SG_NAME="${EXISTING_SG_NAME:-${ENVIRONMENT}-pvc_cluster_sg}"
EXISTING_KEYPAIR_NAME="${EXISTING_KEYPAIR_NAME:-${ENVIRONMENT}-pvc-session-keypair}"

# --- AMI ---
AMI_ID="${AMI_ID:-ami-0a66a47c24c021954}"

# --- Instance group: Cloudera Manager ---
CLDR_MNGR_COUNT="${CLDR_MNGR_COUNT:-1}"
CLDR_MNGR_INSTANCE_TYPE="${CLDR_MNGR_INSTANCE_TYPE:-m5.4xlarge}"
CLDR_MNGR_VOLUME_SIZE="${CLDR_MNGR_VOLUME_SIZE:-300}"

# --- Instance group: FreeIPA / Identity ---
IPA_SERVER_COUNT="${IPA_SERVER_COUNT:-1}"
IPA_SERVER_INSTANCE_TYPE="${IPA_SERVER_INSTANCE_TYPE:-m5.xlarge}"
IPA_SERVER_VOLUME_SIZE="${IPA_SERVER_VOLUME_SIZE:-250}"

# --- Instance group: CDP Base masters ---
PVCBASE_MASTER_COUNT="${PVCBASE_MASTER_COUNT:-1}"
PVCBASE_MASTER_INSTANCE_TYPE="${PVCBASE_MASTER_INSTANCE_TYPE:-m5.4xlarge}"
PVCBASE_MASTER_VOLUME_SIZE="${PVCBASE_MASTER_VOLUME_SIZE:-400}"

# --- Instance group: CDP Base workers ---
PVCBASE_WORKER_COUNT="${PVCBASE_WORKER_COUNT:-3}"
PVCBASE_WORKER_INSTANCE_TYPE="${PVCBASE_WORKER_INSTANCE_TYPE:-m5.4xlarge}"
PVCBASE_WORKER_VOLUME_SIZE="${PVCBASE_WORKER_VOLUME_SIZE:-400}"

# --- Instance group: ECS masters ---
PVCECS_MASTER_COUNT="${PVCECS_MASTER_COUNT:-1}"
PVCECS_MASTER_INSTANCE_TYPE="${PVCECS_MASTER_INSTANCE_TYPE:-m5.8xlarge}"
PVCECS_MASTER_VOLUME_SIZE="${PVCECS_MASTER_VOLUME_SIZE:-1300}"

# --- Instance group: ECS workers ---
PVCECS_WORKER_COUNT="${PVCECS_WORKER_COUNT:-7}"
PVCECS_WORKER_INSTANCE_TYPE="${PVCECS_WORKER_INSTANCE_TYPE:-r5a.4xlarge}"
PVCECS_WORKER_VOLUME_SIZE="${PVCECS_WORKER_VOLUME_SIZE:-1300}"
