---
- name: Stop and disable firewall service
  ansible.builtin.service:
    name: "{{ os_vars[ansible_os_family].firewall_service }}"
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable UFW firewall (Debian family)
  ansible.builtin.command: ufw disable
  when: ansible_os_family == "Debian"
  register: ufw_disable
  changed_when: "'Firewall stopped and disabled' in ufw_disable.stdout"
  failed_when: false
