---
- name: Ozone S3 | Authenticate to Kerberos on SDX
  ansible.builtin.shell:
    cmd: echo '{{ common_password | default(ipaadmin_password, true) }}' | kinit admin
  no_log: true
  delegate_to: "{{ item }}"
  loop: "{{ groups[ecs_model_registry_sdx_group] }}"
  run_once: true

- name: Ozone S3 | Read secret on first SDX host
  ansible.builtin.command:
    cmd: ozone s3 getsecret --om-service-id={{ ecs_model_registry_ozone_service_id }}
  register: ecs_ozone_getsecret
  changed_when: false
  delegate_to: "{{ groups[ecs_model_registry_sdx_group] | first }}"
  run_once: true

- name: Ozone S3 | Parse credentials on SDX host
  ansible.builtin.set_fact:
    ozone_s3_access_key: "{{ ecs_ozone_getsecret.stdout_lines | select('match', '^awsAccessKey=') | first | regex_replace('^awsAccessKey=', '') }}"
    ozone_s3_secret_key: "{{ ecs_ozone_getsecret.stdout_lines | select('match', '^awsSecret=') | first | regex_replace('^awsSecret=', '') }}"
  delegate_to: "{{ groups[ecs_model_registry_sdx_group] | first }}"
  run_once: true
