---
- name: Resolve identity client package names
  ansible.builtin.import_tasks: set_os_facts.yml

- name: Install FreeIPA client packages
  ansible.builtin.package:
    name: "{{ os_vars[ansible_os_family].freeipa_client_packages }}"
    state: present
  register: freeipa_client_package_install
  retries: 3
  delay: 10
  until: freeipa_client_package_install is succeeded
  when: identity_provider_effective == 'freeipa'

- name: Install Active Directory join packages
  ansible.builtin.package:
    name: "{{ os.ad_join_packages }}"
    state: present
  register: ad_client_package_install
  retries: 3
  delay: 10
  until: ad_client_package_install is succeeded
  when: identity_provider_effective == 'ad'
