---
- name: Submit {{ base_cluster_setup_command.command }} for {{ base_cluster_setup_command.service }}
  ansible.builtin.uri:
    url: >-
      {{ cm_cluster_module_api_url }}/clusters/{{ cdh_basecluster_name
      }}/services/{{ base_cluster_setup_command.service
      }}/commands/{{ base_cluster_setup_command.command }}
    method: POST
    user: "{{ cm_admin_user }}"
    password: "{{ cm_admin_pass }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: [200, 400]
    follow_redirects: none
  register: base_cluster_service_setup_command
  failed_when: >-
    base_cluster_service_setup_command.status | int != 200
    and 'already exists' not in (
      (base_cluster_service_setup_command.json | default({})).get(
        'message',
        base_cluster_service_setup_command.msg | default('')
      )
      | lower
    )
    and 'already initialized' not in (
      (base_cluster_service_setup_command.json | default({})).get(
        'message',
        base_cluster_service_setup_command.msg | default('')
      )
      | lower
    )
  delegate_to: "{{ cm_cluster_module_delegate_to }}"

- name: Wait for {{ base_cluster_setup_command.command }} on {{ base_cluster_setup_command.service }}
  ansible.builtin.include_tasks: wait_cm_api_command.yml
  vars:
    cm_krb_api_url: "{{ cm_cluster_module_api_url }}"
    cm_api_command_id: "{{ base_cluster_service_setup_command.json.id }}"
    cm_api_command_allow_already_exists: true
    cm_api_uri_delegate_to: "{{ cm_cluster_module_delegate_to }}"
  when:
    - base_cluster_service_setup_command.status | int == 200
    - base_cluster_service_setup_command.json.id is defined
