[ipaserver]
ipaserver ansible_host=52.221.181.253 private_ip=172.31.30.216 cldr_hostname=ipaserver

[cldr-mngr]
cldr-mngr ansible_host=18.142.60.133 private_ip=172.31.28.247 cldr_hostname=cldr-mngr

[base-masters]
pvcbase-master ansible_host=54.169.201.13 private_ip=172.31.25.204 cldr_hostname=pvcbase-master

[base-workers]
pvcbase-worker1 ansible_host=54.179.186.82 private_ip=172.31.29.42 cldr_hostname=pvcbase-worker1
pvcbase-worker2 ansible_host=3.0.61.86 private_ip=172.31.29.203 cldr_hostname=pvcbase-worker2
pvcbase-worker3 ansible_host=47.129.250.102 private_ip=172.31.28.110 cldr_hostname=pvcbase-worker3

[ecs-masters]
# No hosts found for ecs-masters

[ecs-workers]
# No hosts found for ecs-workers

