[ipaserver]
ipaserver ansible_host=54.169.109.231 cldr_hostname=ipaserver

[cldr-mngr]
cldr-mngr ansible_host=54.251.184.204 cldr_hostname=cldr-mngr

[base-masters]
pvcbase-master ansible_host=54.179.143.18 cldr_hostname=pvcbase-master

[base-workers]
pvcbase-worker1 ansible_host=13.215.153.38 cldr_hostname=pvcbase-worker1

[ecs-masters]
# No hosts found for ecs-masters

[ecs-workers]
# No hosts found for ecs-workers

