collections:
  - name: community.general
  - name: ansible.posix
  - name: community.crypto
  - name: freeipa.ansible_freeipa
  - name: git+https://github.com/cloudera-labs/cloudera.cluster.git,devel
