[ipaserver]
; ipaserver ansible_host=52.221.181.253 private_ip=172.31.30.216 cldr_hostname=ipaserver

[cldr-mngr]
cldr-mngr ansible_host=10.54.75.123 private_ip=10.54.75.123 cldr_hostname=cldr-mngr

[base-masters]
pvcbase-master ansible_host=10.54.75.74 private_ip=10.54.75.74 cldr_hostname=pvcbase-master

[base-workers]
pvcbase-worker1 ansible_host=10.54.75.76 private_ip=10.54.75.76 cldr_hostname=pvcbase-worker1
pvcbase-worker2 ansible_host=10.54.75.45 private_ip=10.54.75.45 cldr_hostname=pvcbase-worker2
pvcbase-worker3 ansible_host=10.54.75.96 private_ip=10.54.75.96 cldr_hostname=pvcbase-worker3

[ecs-masters]
pvcecs-master ansible_host=10.54.75.68 private_ip=10.54.75.68 cldr_hostname=pvcecs-master

[ecs-workers]
pvcecs-worker1 ansible_host=10.54.75.106 private_ip=10.54.75.106 cldr_hostname=pvcecs-worker1
pvcecs-worker2 ansible_host=10.54.75.103 private_ip=10.54.75.103 cldr_hostname=pvcecs-worker2
pvcecs-worker3 ansible_host=10.54.75.72 private_ip=10.54.75.72 cldr_hostname=pvcecs-worker3
pvcecs-worker4 ansible_host=10.54.75.94 private_ip=10.54.75.94 cldr_hostname=pvcecs-worker4
pvcecs-worker5 ansible_host=10.54.75.86 private_ip=10.54.75.86 cldr_hostname=pvcecs-worker5
pvcecs-worker6 ansible_host=10.54.75.46 private_ip=10.54.75.46 cldr_hostname=pvcecs-worker6
pvcecs-worker7 ansible_host=10.54.75.53 private_ip=10.54.75.53 cldr_hostname=pvcecs-worker7

